version: '3.7'

services:
  web:
    container_name: web_todo
    build: .
    #command: python /usr/src/todo/manage.py runserver 0.0.0.0:8000
    command: gunicorn todo.wsgi:application --bind 0.0.0.0:8000
    #tty: true
    #stdin_open: true
    restart: always
    volumes:
      - ./:/usr/src/todo/
      - static_volume:/usr/src/todo/static
    #  - ./ssh:/root/.ssh
    #ports:
    #  - 8000:8000
    expose:
      - 8000
    env_file:
      - ./db_env
    depends_on:
      - db
  db:
    container_name: db_todo
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    container_name: ng_todo
    build: ./nginx
    volumes:
      - static_volume:/usr/src/todo/static
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:  
  static_volume: